// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@lemon.ai"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "用户登录，返回Access Token和Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "退出登录，使Token失效",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "使用Refresh Token刷新Access Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新Token",
                "parameters": [
                    {
                        "description": "刷新Token请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "注册新用户，注册后状态为inactive，需要管理员审核",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/audios": {
            "get": {
                "responses": {}
            },
            "post": {
                "description": "为章节解说生成所有章节音频片段，使用TTS服务生成音频。音频生成是异步的，提交任务后需要通过状态查询接口轮询进度。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "音频生成"
                ],
                "summary": "生成章节音频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "解说ID",
                        "name": "narration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"音频生成任务已提交\\\", \\\"data\\\": {\\\"audio_ids\\\": [\\\"...\\\"], \\\"count\\\": 1, \\\"narration_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/audios/versions": {
            "get": {
                "description": "获取章节解说的所有音频版本号列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "音频生成"
                ],
                "summary": "获取音频版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "解说ID",
                        "name": "narration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {\\\"narration_id\\\": \\\"...\\\", \\\"versions\\\": [1, 2, 3]}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/images": {
            "get": {
                "responses": {}
            },
            "post": {
                "description": "为章节解说生成所有章节图片，使用图片生成服务（Ark API）生成图片。图片生成是异步的，提交任务后需要通过状态查询接口轮询进度。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片生成"
                ],
                "summary": "生成章节图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "解说ID",
                        "name": "narration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"图片生成任务已提交\\\", \\\"data\\\": {\\\"image_ids\\\": [\\\"...\\\"], \\\"count\\\": 1, \\\"narration_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/scenes": {
            "get": {
                "description": "根据 narration_id 获取场景列表（按 sequence 排序）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "获取解说场景列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "解说ID",
                        "name": "narration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/shots": {
            "get": {
                "description": "根据 narration_id 获取镜头列表（按 index 排序）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "获取解说镜头列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "解说ID",
                        "name": "narration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/subtitles": {
            "get": {
                "responses": {}
            },
            "post": {
                "description": "为章节解说生成所有字幕文件（ASS格式），为每个 narration shot 生成单独的字幕文件，与音频片段一一对应。需要先有章节音频记录（包含时间戳数据）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字幕生成"
                ],
                "summary": "生成章节字幕",
                "parameters": [
                    {
                        "type": "string",
                        "description": "解说ID",
                        "name": "narration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"字幕生成任务已提交\\\", \\\"data\\\": {\\\"subtitle_ids\\\": [\\\"...\\\"], \\\"count\\\": 1, \\\"narration_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/narrations/{narration_id}/version": {
            "put": {
                "description": "设置章节解说的版本号。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "设置解说版本号",
                "parameters": [
                    {
                        "description": "设置版本请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.SetNarrationVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"版本号设置成功\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels": {
            "post": {
                "description": "根据资源ID创建小说，返回小说ID。这是小说处理流程的第一步。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "小说管理"
                ],
                "summary": "创建小说",
                "parameters": [
                    {
                        "description": "创建小说请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.CreateNovelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"小说创建成功\\\", \\\"data\\\": {\\\"novel_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/images/versions": {
            "get": {
                "description": "获取章节的所有图片版本号列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片生成"
                ],
                "summary": "获取图片版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {\\\"chapter_id\\\": \\\"...\\\", \\\"versions\\\": [1, 2, 3]}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/narration": {
            "get": {
                "description": "根据章节ID获取章节解说，返回最新版本的解说信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "获取章节解说",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "解说不存在",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "为单一章节生成解说文本，返回JSON格式的解说内容。解说内容会保存到数据库，包括场景和镜头信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "生成章节解说",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"解说生成成功\\\", \\\"data\\\": {\\\"narration_text\\\": \\\"...\\\", \\\"chapter_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/narration/manual": {
            "post": {
                "description": "人工提交解说 JSON 文本，服务端解析/校验并生成新的解说版本（写入 narrations/scenes/shots）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "人工提交解说并生成新版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.ManualNarrationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/narration/version/{version}": {
            "get": {
                "description": "根据章节ID和版本号获取指定版本的章节解说信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "获取指定版本的章节解说",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "版本号",
                        "name": "version",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "解说不存在",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/narration/versions": {
            "get": {
                "description": "获取章节的所有解说版本号列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "获取章节解说版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {\\\"chapter_id\\\": \\\"...\\\", \\\"versions\\\": [1, 2, 3]}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/narrations": {
            "get": {
                "description": "列出指定章节的所有解说版本（包含 narration_id、version、prompt、status）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "列出章节解说版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/subtitles/versions": {
            "get": {
                "description": "获取章节的所有字幕版本号列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字幕生成"
                ],
                "summary": "获取字幕版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {\\\"chapter_id\\\": \\\"...\\\", \\\"versions\\\": [1, 2, 3]}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/videos": {
            "get": {
                "responses": {}
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/videos/final": {
            "post": {
                "description": "拼接所有 narration 视频，添加 finish.mp4，生成章节的最终完整视频。需要确保所有 narration 视频已完成（status=completed）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频生成"
                ],
                "summary": "生成章节的最终完整视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"最终视频生成成功\\\", \\\"data\\\": {\\\"video_id\\\": \\\"...\\\", \\\"chapter_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误（如没有找到 narration 视频）",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/videos/narration": {
            "post": {
                "description": "为章节生成所有 narration 视频，所有分镜都单独生成视频，使用图生视频方式（Ark API 或 FFmpeg）。视频生成是异步的，提交任务后需要通过状态查询接口轮询进度。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频生成"
                ],
                "summary": "生成章节的 narration 视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"视频生成任务已提交\\\", \\\"data\\\": {\\\"video_ids\\\": [\\\"...\\\"], \\\"count\\\": 1, \\\"chapter_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/chapters/{chapter_id}/videos/versions": {
            "get": {
                "description": "获取章节的所有视频版本号，用于查看历史版本或选择特定版本。每次生成视频都会创建新版本。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频查询"
                ],
                "summary": "获取章节的视频版本号列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"versions\\\": [1, 2, 3], \\\"count\\\": 3, \\\"chapter_id\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}": {
            "get": {
                "description": "根据小说ID获取小说的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "小说管理"
                ],
                "summary": "获取小说信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小说ID",
                        "name": "novel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"novel\\\": {...}}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}/chapters": {
            "get": {
                "description": "根据小说ID获取该小说的所有章节列表，按序号排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "章节管理"
                ],
                "summary": "获取章节列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小说ID",
                        "name": "novel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"novel_id\\\": \\\"...\\\", \\\"chapters\\\": [...], \\\"count\\\": 10}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}/chapters/narration": {
            "post": {
                "description": "并发地为小说的所有章节生成解说文本。这是一个异步操作，会为每个章节生成解说并保存到数据库。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "解说管理"
                ],
                "summary": "为所有章节生成解说",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小说ID",
                        "name": "novel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"所有章节解说生成任务已提交\\\", \\\"data\\\": {\\\"novel_id\\\": \\\"...\\\", \\\"message\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}/chapters/split": {
            "post": {
                "description": "根据小说内容切分章节，将小说文本按照目标章节数切分成多个章节。这是小说处理流程的第二步。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "章节管理"
                ],
                "summary": "切分章节",
                "parameters": [
                    {
                        "description": "切分章节请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.SplitChaptersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"章节切分成功\\\", \\\"data\\\": {\\\"novel_id\\\": \\\"...\\\", \\\"target_chapters\\\": 10, \\\"message\\\": \\\"已切分为 10 个章节\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}/characters": {
            "get": {
                "description": "获取小说的所有角色列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "获取小说角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小说ID",
                        "name": "novel_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": [...]}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}/characters/sync": {
            "post": {
                "description": "从章节解说同步角色信息到小说级别，提取解说中的角色信息并保存到角色表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "同步角色信息",
                "parameters": [
                    {
                        "description": "同步角色请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.SyncCharactersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"角色同步成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novels/{novel_id}/characters/{name}": {
            "get": {
                "description": "根据名称获取角色信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "获取角色信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小说ID",
                        "name": "novel_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"获取成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "角色不存在",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/resources": {
            "get": {
                "description": "查询资源列表，支持按用户ID、扩展名、状态等条件筛选，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资源管理"
                ],
                "summary": "查询资源列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件扩展名筛选",
                        "name": "ext",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态筛选",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码（默认1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量（默认20，最大100）",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"resources\\\": [...], \\\"total\\\": 100, \\\"page\\\": 1, \\\"page_size\\\": 20}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/resources/upload": {
            "post": {
                "description": "通过 multipart/form-data 上传文件到服务端，服务端会保存文件并创建资源记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资源管理"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传的文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID（可选，如果为空则从认证信息中获取）",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"文件上传成功\\\", \\\"data\\\": {\\\"resource_id\\\": \\\"...\\\", \\\"resource_url\\\": \\\"...\\\", \\\"file_size\\\": 1024, \\\"file_name\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/resources/{resource_id}": {
            "get": {
                "description": "根据资源ID获取资源的详细信息（元数据，不包含文件内容）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资源管理"
                ],
                "summary": "获取资源信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "资源ID",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"resource\\\": {...}}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/resources/{resource_id}/download": {
            "get": {
                "description": "根据资源ID下载文件，返回文件流",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "资源管理"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "资源ID",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件流",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/resources/{resource_id}/download-url": {
            "get": {
                "description": "根据资源ID获取预签名的下载URL，适用于客户端直接下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资源管理"
                ],
                "summary": "获取下载URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "资源ID",
                        "name": "resource_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "过期时间（秒，默认3600）",
                        "name": "expires_in",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"resource_id\\\": \\\"...\\\", \\\"download_url\\\": \\\"...\\\", \\\"expires_at\\\": \\\"...\\\", \\\"file_name\\\": \\\"...\\\", \\\"file_size\\\": 1024, \\\"content_type\\\": \\\"...\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/resource.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/videos": {
            "get": {
                "description": "根据状态查询视频列表，用于轮询视频生成进度。支持的状态：pending（待处理）、processing（处理中）、completed（已完成）、failed（失败）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频查询"
                ],
                "summary": "根据状态查询视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "视频状态：pending, processing, completed, failed",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应\"  \"{\\\"code\\\": 0, \\\"message\\\": \\\"success\\\", \\\"data\\\": {\\\"videos\\\": [...], \\\"count\\\": 1, \\\"status\\\": \\\"pending\\\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误（如 status 参数无效）",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/novel.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflow": {
            "post": {
                "description": "创建新的工作流实例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流"
                ],
                "summary": "创建工作流",
                "parameters": [
                    {
                        "description": "创建工作流请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workflow.CreateWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/workflow.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/workflow.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflow/{id}/start": {
            "post": {
                "description": "启动待处理的工作流，开始执行剧本生成流程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作流"
                ],
                "summary": "启动工作流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工作流ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/workflow.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/workflow.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务健康状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "检查服务是否就绪",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查"
                ],
                "summary": "就绪检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码（非0表示错误）",
                    "type": "integer"
                },
                "detail": {
                    "description": "错误详情（可选）",
                    "type": "string"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码（必填）",
                    "type": "string"
                },
                "username": {
                    "description": "用户名（必填）",
                    "type": "string"
                }
            }
        },
        "auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "Refresh Token（必填）",
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱（必填，需符合邮箱格式）",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称（可选）",
                    "type": "string"
                },
                "password": {
                    "description": "密码（必填，至少6位）",
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "description": "用户名（必填，3-50字符）",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "novel.CreateNovelRequest": {
            "type": "object",
            "required": [
                "resource_id",
                "user_id",
                "workflow_id"
            ],
            "properties": {
                "resource_id": {
                    "description": "资源ID（必填）",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户ID（必填）",
                    "type": "string"
                },
                "workflow_id": {
                    "description": "工作流ID（必填）",
                    "type": "string"
                }
            }
        },
        "novel.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码（非0表示错误）",
                    "type": "integer"
                },
                "detail": {
                    "description": "错误详情（可选）",
                    "type": "string"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string"
                }
            }
        },
        "novel.ManualNarrationRequest": {
            "type": "object",
            "required": [
                "narration_text",
                "user_id"
            ],
            "properties": {
                "narration_text": {
                    "description": "解说 JSON 文本（必填）",
                    "type": "string"
                },
                "prompt": {
                    "description": "生成提示词（可选，便于记录）",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户ID（必填）",
                    "type": "string"
                }
            }
        },
        "novel.SetNarrationVersionRequest": {
            "type": "object",
            "required": [
                "narration_id",
                "version"
            ],
            "properties": {
                "narration_id": {
                    "description": "解说ID（必填）",
                    "type": "string"
                },
                "version": {
                    "description": "版本号（必填）",
                    "type": "integer"
                }
            }
        },
        "novel.SplitChaptersRequest": {
            "type": "object",
            "required": [
                "novel_id",
                "target_chapters"
            ],
            "properties": {
                "novel_id": {
                    "description": "小说ID（必填）",
                    "type": "string"
                },
                "target_chapters": {
                    "description": "目标章节数（必填，至少1章）",
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "novel.SyncCharactersRequest": {
            "type": "object",
            "required": [
                "narration_id",
                "novel_id"
            ],
            "properties": {
                "narration_id": {
                    "description": "解说ID（必填）",
                    "type": "string"
                },
                "novel_id": {
                    "description": "小说ID（必填）",
                    "type": "string"
                }
            }
        },
        "resource.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码（非0表示错误）",
                    "type": "integer"
                },
                "detail": {
                    "description": "错误详情（可选）",
                    "type": "string"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string"
                }
            }
        },
        "workflow.CreateWorkflowRequest": {
            "type": "object",
            "required": [
                "input_type",
                "name",
                "narration_type"
            ],
            "properties": {
                "input_type": {
                    "description": "text 或 file",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "narration_type": {
                    "description": "旁白类型：narration（旁白/解说）或 dialogue（真人对话）",
                    "type": "string"
                },
                "resource_id": {
                    "type": "string"
                },
                "resource_source": {
                    "type": "string"
                },
                "text_content": {
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID 保留给兼容用途，正常情况下应从认证中间件注入的 context 中获取",
                    "type": "string"
                }
            }
        },
        "workflow.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码（非0表示错误）",
                    "type": "integer"
                },
                "detail": {
                    "description": "错误详情（可选）",
                    "type": "string"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Lemon API",
	Description:      "Lemon is an AI-powered API service built with Eino framework.\nIt provides LLM chat, intelligent agent, and more AI capabilities.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
